import React from 'react';

import Layout from '../components/Layout';

import Scroll from '../components/Scroll';

import pic1 from '../assets/images/pic01.jpg';
import pic2 from '../assets/images/pic02.jpg';
import pic3 from '../assets/images/pic03.jpg';
import config from '../../config';
const IndexPage = () => (
  <Layout>
    <section id="banner">
      <div className="inner">
        <h2>{config.heading}</h2>
        <p>{config.subHeading}</p>
        <ul className="actions special">
          <li>
            <Scroll type="id" element="one">
              <a href="/#" className="button primary">
                CONTACT US
              </a>
            </Scroll>
          </li>
        </ul>
      </div>
      <Scroll type="id" element="one">
        <a href="#one" className="more">
          Learn More
        </a>
      </Scroll>
    </section>

    <section id="one" className="wrapper style1 special">
      <div className="inner">
        <header className="major">
          <h2>
            Progressive Web App Development  
            <br />
            <br />
            
          </h2>
          <p>
            Currently over 70% of online traffic is generated by mobile devices. PWA's are the most effective and cost efficient solution
            to engage with users.
            <br />
            Providing an incredible mobile app experience that leads to a higher conversion rate.
            PWA's have the added benifit of native mobile applications which are easily accessible by merely sharing the url.
          </p>
        </header>
        <ul className="icons major">
          <li>
            <span className="icon fa-gem major style1">
              <span className="label">Lorem</span>
            </span>
          </li>
          <li>
            <span className="icon fa-heart major style2">
              <span className="label">Ipsum</span>
            </span>
          </li>
          <li>
            <span className="icon solid fa-code major style3">
              <span className="label">Dolor</span>
            </span>
          </li>
        </ul>
      </div>
    </section>

    <section id="two" className="wrapper alt style2">
      <section className="spotlight">
        <div className="image">
          <img src={pic1} alt="" />
        </div>
        <div className="content">
          <h2>
            E-commerce Applications
            <br />
            
          </h2>
          <p>
            Blazing fast sites lead to less cart abandons. Ability to add app to Home screen
            allows for personalised marketing campaigns using push notifications. PWA's win with SEO so advertising campaigns are more effective and can be personalised further by accessing the user Geo-location
            from the device. PWA's enable the e-commerce application to work offline with low or even no internet connection.
          </p>
        </div>
      </section>
      <section className="spotlight">
        <div className="image">
          <img src={pic2} alt="" />
        </div>
        <div className="content">
          <h2>
            Custom web apps
            </h2>
            <h4>Increase conversions</h4>
            
          
          <p>
            PWA's usually load in 2 seconds, decreasing the bounce rate and instantly engaging users.
            <br />
            The development process is equally fast and cost effective compared with traditional mobile app development.
            A well designed Web App is usually the hardest working employee of a company and usually a customers first touch point. Make a great first impression!
          </p>
        </div>
      </section>
      <section className="spotlight">
        <div className="image">
          <img src={pic3} alt="" />
        </div>
        <div className="content">
          <h2>
            Digital Marketing
          </h2>
          <p>
            The best place to hide a dead body is in page 2 of Google search results.
             We at MAVDigital are experts in optimising an applications copy and content in order to achieve great SEO rankings.
              MAVDigital is a full service Digital Marketing company specialising in brand development and management across all channels. Let us guide you in the art of building and engaging an audience.

          </p>
        </div>
      </section>
    </section>

    <section id="three" className="wrapper style3 special">
      <div className="inner">
        <header className="major">
          <h2>PWA features</h2>
          <p>
           Progressive Web App (PWA) are a new class of application introduced by Google
           and promoted by Microsoft and Apple. It offers an incredible mobile app experience that is highly optimised,
           reliable and accessible.
          </p>
        </header>
        <ul className="features">
          <li className="icon fa-paper-plane">
            <h3>Offline-first</h3>
            <p>
              Your app works even when the user has low or even no internet connection.
            </p>
          </li>
          <li className="icon solid fa-laptop">
            <h3>Cross-platform development</h3>
            <p>
              Build once, run on any device. Cross platform, performant applications for your 
              site or store.
            </p>
          </li>
          <li className="icon solid fa-code">
            <h3>Blazing fast</h3>
            <p>
              Engage customers with blazing fast loading times and optimisations out the box.
            </p>
          </li>
          <li className="icon solid fa-headphones-alt">
            <h3>Home screen icon</h3>
            <p>
              Enables users to save app to their home screen on mobile.
            </p>
          </li>
          <li className="icon fa-heart">
            <h3>Push notifications</h3>
            <p>
              Stay connected with users by personalising campaigns
              driving conversions and increasing customer loyalty.
            </p>
          </li>
          <li className="icon fa-flag">
            <h3>Native mobile features</h3>
            <p>
              Run a more effective campaign with access to native mobile features such as 
              geo-location, users camera, bluetooth. The possibilities are endless.
            </p>        
          </li>
        </ul>
      </div>
    </section>

    <section id="cta" className="wrapper style4">
      <div className="inner">
        <header>
          <h2>YES, I WANT A Progressive Web App! </h2>
          <p>
            We do follow a tried and tested process, however the underlying goal is always TO GET YOU TO MARKET, FAST!

          </p>
        </header>
        <ul className="actions stacked">
          <li>
            <a href="/#" className="button fit primary">
              I WANT A PWA!
            </a>
          </li>
          <li>
            <a href="/#" className="button fit">
              Learn More
            </a>
          </li>
        </ul>
      </div>
    </section>
  </Layout>
);

export default IndexPage;
